### ISSUE TITLE
Know what you got banned for / Rewrite Ban-System

### ISSUE THREAD

**Issue by ernst451** [ernstchan/phutaba#10]
There has to be a link on the ban site, so users know for which post they got banned for.
-> Better: Render the affected post on the ban page.

Correctly support IPv6
Bans for individual or all boards
Expiration date for bans
Also see issues #33 and #34.

**Comment by ProtoFoo** [comment]
>Correctly support IPv6
- done
>Expiration date for bans
- done

**Comment by ProtoFoo** [comment]
[x] link on the ban site, so users know for which post they got banned for.
